services:
  - type: web
    name: plot-doi-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://plot-doi-frontend.onrender.com

  - type: web
    name: plot-doi-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
